# Generated by Django 5.2.1 on 2025-07-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0002_user_following_posts"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Posts",
            new_name="Post",
        ),
    ]
