# Generated by Django 5.2.1 on 2025-10-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Tracker", "0003_alter_category_name_alter_transaction_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
