# Generated by Django 5.2.1 on 2025-05-25 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flights", "0002_airports_alter_flight_destination_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Airports",
            new_name="Airport",
        ),
    ]
