# Generated by Django 5.2.1 on 2025-06-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionListing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField()),
                ("item_description", models.CharField()),
                ("start_bid", models.IntegerField()),
            ],
        ),
    ]
