# Generated by Django 5.2.1 on 2025-06-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_auctionlisting"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="item_link",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="start_bid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
