# Generated by Django 5.2.1 on 2025-06-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0003_auctionlisting_item_link_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="item_link",
            new_name="image_link",
        ),
    ]
