# Generated by Django 5.2.1 on 2025-06-05 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_rename_item_link_auctionlisting_image_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="start_bid",
            new_name="bid",
        ),
    ]
