# Generated by Django 5.2.1 on 2025-06-05 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_rename_start_bid_auctionlisting_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="bid",
            new_name="bid_price",
        ),
    ]
