# Generated by Django 5.2.1 on 2025-06-05 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0006_rename_bid_auctionlisting_bid_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="bid_price",
            new_name="start_bid",
        ),
    ]
