# Generated by Django 5.2.1 on 2025-06-05 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_rename_bid_price_auctionlisting_start_bid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="start_bid",
            new_name="bid_price",
        ),
    ]
