# Generated by Django 5.2.1 on 2025-06-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0008_rename_start_bid_auctionlisting_bid_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="image_link",
            field=models.URLField(blank=True),
        ),
    ]
