# Generated by Django 5.2.1 on 2025-06-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0009_alter_auctionlisting_image_link"),
    ]

    operations = [
        migrations.RenameField(
            model_name="auctionlisting",
            old_name="bid_price",
            new_name="start_bid",
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="image_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
