# Generated by Django 5.2.1 on 2025-06-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_auctionlisting_category_auctionlisting_created_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="current_bid",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
