# Generated by Django 5.2.1 on 2025-06-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0013_alter_auctionlisting_created_by_comments"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="username",
            new_name="author",
        ),
    ]
