# Generated by Django 5.2.1 on 2025-06-14 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_rename_username_comments_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="comments",
            new_name="comment",
        ),
    ]
