# Generated by Django 5.2.1 on 2025-06-19 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0017_category_alter_auctionlisting_item_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionlisting",
            name="category",
        ),
        migrations.AddField(
            model_name="auctionlisting",
            name="categories",
            field=models.ManyToManyField(
                related_name="listings", to="auctions.category"
            ),
        ),
    ]
