# Generated by Django 5.2.1 on 2025-06-19 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0018_remove_auctionlisting_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auctionlisting",
            name="categories",
        ),
        migrations.AddField(
            model_name="auctionlisting",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="listings",
                to="auctions.category",
            ),
        ),
    ]
