# Generated by Django 5.2.1 on 2025-06-19 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0019_remove_auctionlisting_categories_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="image_link",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
