# Generated by Django 5.2.1 on 2025-06-21 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0021_alter_auctionlisting_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auctionlisting",
            name="image_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auctionlisting",
            name="item_description",
            field=models.CharField(),
        ),
    ]
